apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yt-download-api-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homelab-storage
  resources:
    requests:
      storage: 10Gi
